mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
	def get_success_url(selfself,request, user):
		return 'rango/add_profile/'


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^$', 'rango.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^rango/', include('rango.urls', namespace="rango")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
	url(r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
	urlpatterns += patterns(
		'django.views.static',
		(r'^media/(?P<path>.*)',
		'serve',
		{'document_root': settings.MEDIA_ROOT}), )

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
		url(r'^$', views.index, name='index'), 
		url(r'^about/$', views.about, name='about'),
		url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
		url(r'^add_category/$', views.add_category, name='add_category'),
		url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
		#url(r'^register/$', views.register, name='register'),
		#url(r'^login/$', views.user_login, name='login'),
		url(r'^restricted/$', views.restricted, name='restricted'),
		#url(r'^logout/$', views.user_logout, name='logout'),
		#url(r'^search/$', views.search, name='search'),
		url(r'^goto/', views.track_url, name='goto'),
		url(r'^add_profile/$', views.register_profile, name='add_profile'),
		url(r'^profile/$', views.profile, name='profile'),
		url(r'^like_category/$', views.like_category, name='like_category'),
		url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
		url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page'),
		
		)
		

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique=False)
	
	def save(self, *args, **kwargs):
			self.slug = slugify(self.name)
			super(Category, self).save(*args, **kwargs)
			
			if self.views < 0:
				self.views = 0
	
	def __unicode__(self):
			return self.name
		
class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.title
		
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)
	
	def __unicode__(self):
		return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=128, help_text="Please enter the category name.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)
	
	class Meta:
		model = Category
		fields = ('name',)
		
class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
	url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	
	def clean(self):
		cleaned_data = self.cleaned_data
		url = cleaned_data.get('url')
		
		if url and not url.startswith('http://'):
			url = 'http://' + url
			cleaned_data['url'] = url
		return cleaned_data
	class Meta:
		model = Page
		exclude = ('category',)
		
class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password')
		
class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from rango.bing_search import run_query

def index(request):
	category_list = Category.objects.order_by('-likes')[:5]
	page_list = Page.objects.order_by('-views')[:5]
	context_dict = {'categories': category_list,'pages': page_list}
	
	visits = request.session.get('visits')
	#does a cookie for visits exist?
	#if it doesn't create one and set it to 1
	if not visits:
		visits = 1
	reset_last_visit_time = False
	
	#does a cookie for the last visit exist?
	last_visit = request.session.get('last_visit')
	if last_visit:
		last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
		#if it does convert it to a string
		
		if (datetime.now() - last_visit_time).days > 0:
			visits = visits + 1
			reset_last_visit_time = True
			#if last visit was beyond a day then reset visit time
	else:
		reset_last_visit_time = True
		#if the cookie doesn't exist, reset the visit time
	
	#update last visit and number of visits
	if reset_last_visit_time:
		request.session['last_visit'] = str(datetime.now())
		request.session['visits'] = visits
	#add visits to the context dictionary so it can be used on a page
	context_dict['visits'] = visits
	
	response = render(request, 'rango/index.html', context_dict)
	
	return response
	
def about(request):
	context_dict = {'visits': request.session['visits']}
	return render(request, 'rango/about.html', context_dict)
	
def category(request, category_name_slug):
	context_dict = {}
	
	try:
		category = Category.objects.get(slug=category_name_slug)
		context_dict['category_name'] = category.name
		
		pages = Page.objects.filter(category=category)
		
		context_dict['pages'] = pages
		
		context_dict['category'] = category
		
		
	except Category.DoestNotExist:
		pass
		
	result_list = []
	
	if request.method == 'POST':
		query = request.POST['query'].strip()
		
		if query:
			result_list = run_query(query)
			context_dict['result_list'] = result_list	
			context_dict['query'] = query
			
#	if not context_dict.get('query'):
	#	query = category.name
	#	context_dict['query'] = query
#		result_list = run_query(query)		
#		context_dict['result_list'] = result_list
		
	return render(request, 'rango/category.html', context_dict)
	
@login_required	
def add_category(request):
	if request.method == 'POST':
		form = CategoryForm(request.POST)
		
		if form.is_valid():
			form.save(commit=True)
			
			return index(request)
		else:
			print form.errors
	else:
		form = CategoryForm()
		
	return render(request, 'rango/add_category.html', {'form': form})
	
@login_required	
def add_page(request, category_name_slug):
	
	try:
		cat = Category.objects.get(slug=category_name_slug)
	except Category.DoesNotExist:
		cat = None
		
	if request.method == 'POST':
		form = PageForm(request.POST)
		if form.is_valid():
			if cat:
				page = form.save(commit=False)
				page.category = cat
				page.views = 0
				page.save()
				
				return category(request, category_name_slug)
		else:
			print form.errors
			
	else:
		form = PageForm()

	context_dict = {'form':form, 'category': cat, 'category_name_slug':category_name_slug }
	
	return render(request, 'rango/add_page.html', context_dict)


@login_required
def restricted(request):
	return render(request, 'rango/restricted.html')
	

def track_url(request):
	page_id = None
	url = '/rango/'
	if request.method == 'GET':
		if 'page_id' in request.GET:
			page_id = request.GET['page_id']
			try:
				page = Page.objects.get(id=page_id)
				page.views = page.views + 1
				page.save()
				url = page.url
			except:
				pass
	return redirect(url)	
	
	
def register_profile(request):
	if request.method =='POST':
		profile_form = UserProfileForm(data=request.POST)
		
		if profile_form.is_valid():
			
			profile = profile_form.save(commit=False)
			profile.user = request.user
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
				
			profile.save()
			
			render(request, '/rango/')
			
		else:
			print profile_form.errors
	
	else:
		profile_form = UserProfileForm()
		
	return render(request, 'rango/profile_registration.html', {'profile_form' : profile_form})	
	
def profile(request):
	user = request.user
	context_dict = {'user': user, 'userprofile': user.userprofile }
	return render(request, 'rango/profile.html', context_dict)
	
	
	
	
@login_required
def like_category(request):
	cat_id = None
	if request.method == 'GET':
		cat_id = request.GET['category_id']
		
	likes = 0
	if cat_id:
		cat = Category.objects.get(id=int(cat_id))
		if cat:
			likes = cat.likes + 1
			cat.likes = likes
			cat.save()
			
	return HttpResponse(likes)
	
def get_category_list(max_results=0, starts_with=''):
	cat_list = []
	if starts_with:
			cat_list = Category.objects.filter(name__istartswith=starts_with)
			
	if max_results > 0:
		if len(cat_list) > max_results:
			cat_list = cat_list[:max_results]
			
	return cat_list
	
def suggest_category(request):
	
	cat_list = []
	starts_with = ''
	if request.method == 'GET':
		starts_with = request.GET['suggestion']
		
	cat_list = get_category_list(8, starts_with)
	
	return render(request, 'rango/category_list.html', {'cat_list': cat_list })

@login_required
def auto_add_page(request):
	cat_id = None
	url = None
	title = None
	context_dict = {}
	if request.method == 'GET':
		cat_id = request.GET['category_id']
		url = request.GET['url']
		title = request.GET['title']
		if cat_id:
			category = Category.objects.get(id=int(cat_id))
			p = Page.objects.get_or_create(category=category, title=title, url=url)
			
			pages = Page.objects.filter(category=category).order_by('-views')
			
			context_dict['pages'] = pages
			
	return render(request, 'rango/page_list.html', context_dict)


#####LEGACY CODE#######
#def search(request):
#	result_list = []
#	
#	if request.method == 'POST':
#		query = request.POST['query'].strip()
##		
#		if query:
#			result_list = run_query(query)
#			
#	return render(request, 'rango/search.html', {'result_list': result_list})
		
	
#def register(request):
#	
#	if request.method == 'POST':
#	
#		user_form = UserForm(data=request.POST)
#		profile_form = UserProfileForm(data=request.POST)
#		
#		if user_form.is_valid() and profile_form.is_valid():
#			user = user_form.save()
#			
#			user.set_password(user.password)
#			user.save()
#			
#			profile = profile_form.save(commit=False)
#			profile.user = user
#			
#			if 'picture' in request.FILES:
#				profile.picture = request.FILES['picture']
#				
#			profile.save()
#			
#			return HttpResponseRedirect('/rango/login/')
			#Direct to login if registered
			
			
#		else:
#			print user_form.errors, profile_form.errors
			
#	else:
#		user_form = UserForm()
#		profile_form = UserProfileForm()
	
		
#	return render(request, 
#			'rango/register.html',
#			{'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )
			
#def user_login(request):
	
#	if request.method == 'POST':
#		username = request.POST['username']
#		password = request.POST['password']
		
#		user = authenticate(username=username, password=password)
		
#		if user:
#			if user.is_active:
#				login(request, user)
#				return HttpResponseRedirect('/rango/')
#			else:
#				return HttpResponse("Your Rango account is disabled.")
#		else:
#			print "Invalid login details: {0}, {1}".format(username, password)
#		return HttpResponse("Invalid login details supplied.")
		
#	else:
#		return render(request, 'rango/login.html', {})
		
	


#def user_logout(request):
#	logout(request)
	
#	return HttpResponseRedirect('/rango/')

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %} About {% endblock %}
	
{% block body_block %}
	<div class="page-header">
		<h1> About </h1>
		</div>
		<div>
		<p> Rango says welcome to the about page<br /></p>
		<p> You have visited the website a total of {{ visits }} times </p>
		<button id="about-btn">Click Me - I'm javascript on speed </button> 
		<img src="{% static "images/therango.jpg" %}" alt="Picture of Rango" />
		</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}Add Category{% endblock %}
{% block body_block %}

		<form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
	<h2 class="form-signin-heading">Add a Category </h2>
		
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}<br />
				{{ field }}<br />
			{% endfor %}
			
			<br />
		<button class="btn btn-primary" type="submit" name="submit">Add Category</button>
		</form>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{%block title %}Add Page{% endblock %}
{% block body_block %}
{% if category %}
		<form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
	<h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}/">{{ category.name }}</a></h2>
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}<br />
				{{ field }}<br />
			{% endfor %}
		<br />
	<button class="btn btn-primary" type="submit" name="submit">Add Page</button>
		</form>
	{% else %}
	<p>This category does not exist.</p>
{% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
<script src="{% static "js/jquery-1.11.2.js" %}"></script>
<script src="{% static "js/rango-jquery.js" %}"></script>
<script src="{% static "js/rango-ajax.js" %}"></script>


<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

</div>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'rango:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'rango:profile' %}">Profile</a></li>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                                <li><a href="{% url 'rango:about' %}">About</a></li>

              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
        	<ul class="nav nav-ist">
        		<li class="nav-header">Find a Category</li>
        		<form>
        		<label></label>
        		<li><input class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
        		</form>
        	</ul>
        	
        	<div id="cats">
			</div>
        		{% load rango_extras %}
                {% block side_block %}
                {% get_category_list category %}
                {% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

	{% block title %}{{ category_name }}{% endblock %}


{%block body_block %}
	<div class="page-header">
		<h1>{{ category_name }}</h1>
	</div>
		{% if category %}
		<div id="pages">
			{% if pages %}
			<ul>
				{% for page in pages %}
				<li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a></li>
				{% endfor %}
			</ul>
			{% else %}
				<strong>No pages currently in category.</strong>
				<br />
			{% endif %}
			
		</div>
			<p>
			<strong id="like_count">{{ category.likes }}</strong> people like this category</p>
			{% if user.is_authenticated %}
					<button id="likes" data-catid="{{category.id}}" class="btn btn-primary" type="button">
					<span class="glyphicon glyphicon-thumbs-up"></span>
					Like
					</button>
			</p>
			<a href="{% url 'rango:add_page' category.slug %}"><h4>Add a Page</h4></a>
			<br />

			<br />
	<h4> Didn't find the page you wanted? Search below </h4>
				
	<div class="row">
		<div class="panel panel-primary">
			<br />
			
			<form class="form-inline" id="user_form" method="post" action="{% url 'rango:category' category.slug %}">
				{% csrf_token %}
				
				<input class="form-control" type="text" size="50" name="query" value="" id="query" />
				<input class="btn btn-primary" type="submit" name="submit" value="Search" />
				<br />
			</form>
			
			<div class="panel">
				{% if result_list %}
					<div class="panel-heading">
					<h3 class="panel-title">Results</h3>
					
					<div class="panel-body">
						<div class="list-group">
							{% for result in result_list %}
								<div class="list-group-item">
									<h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
									<button data-catid="{{category.id}}" data-title="{{result.title}}" data-url="{{ result.link }}" class="rango-add btn btn-mini btn-info" type="button">Add</button> 
									<p class="list-group-item-text">{{ result.summary }}</p>
								</div>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			</div>
		</div>
</div>
		{% endif %}
		{% else %}
			The specified category {{ category_name }} does not exist!
		{% endif %}
{% endblock %}

templates/rango/category_list.html
<ul class="nav nav-list">
	{% if cat_list %}
		{% for cat in cat_list %}
			<li><a href="{% url 'rango:category' cat.slug %}">{{ cat.name }}</a></li>
			
			{% endfor %}
		{% else %}
			<li>No categories present.</li>
		{% endif %}
</ul>

templates/rango/cats.html
{% if cats %}
	<ul class="nav nav-sidebar">
		{% for c in cats %}
			{% if c == act_cat %} <li class="active" > {% else %} <li> {% endif %}
			<a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a></li>
		{% endfor %}
		
{% else %}
	<li><strong>There are no categories present.</strong></li>

	</ul>
{% endif %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %} 

{% block body_block %}
	<div class="page-header">
		{% if user.is_authenticated %}
		<h1>Rango says...hello {{ user.username }}!</h1>
		{% else %}
		<h1>Rango says...hello world!</h1>
		{% endif %}
	</div>
		<div class="row placeholders">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Categories</h3>
				</div>
			</div>
				{% if categories %}
					<ul class="list-group">
						{% for category in categories %}
						<li class="list-group-item"><a href="{% url 'rango:category' category.slug %}">{{ category.name }}</a></li> 
						{% endfor %}
					</ul>
				{% else %}
					<strong>There are no categories present. </strong>
				{% endif %}
		
			
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Pages</h3>
				</div>
			</div>
					{% if pages %}
						<ul class="list-group">
							{% for page in pages %}
							<li class="list-group-item">{{ page.title }} </li>
							{% endfor %}
						</ul>
					{% else %}
						<strong>There are no pages present</strong>
					{% endif %}
		</div>
	<p> You have visited the website a total of {{ visits }} times </p>
	<img src="{% static "images/therango.jpg" %}" alt="Picture of Rango" /><br />
{% endblock %}
	


templates/rango/newbase.html
<!doctype html>
<html lang="en">
	<head>
		<meta charset+"utf-8">
		<meta http_equiv=X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, intial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="http://getbootstrap.com/favicon.ico">
		<title>Rango - {% block title %} How to Tango with Django! { %endblock %}</title>
		
		<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
		<link href="http://getbootstrap.com/examples/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->		
		
	</head>
	<body>
		
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                        <li><a href="{% url 'about' %}">About</a></li>

              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}{% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango/page_list.html
{% if pages %}
	<ul>
		{% for page in pages %}
		<li>
			<a href="/rango/goto?page_id={{page.id}}">{{page.title}}</a>
			{% if page.views > 1 %}
				- ({{ page.views }} views)
			{% elif page.views == 1%}
				- ({{ page.views }} view)
			{% endif %}
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<strong> No pages curently in category.</strong><br />
{% endif %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% block body_block %}
		<h1>Profile Registration</h1>
		
		<form id="userprofile_form" method="post" action="{% url 'rango:add_profile' %}" enctype="multipart/form-data">
		
			{% csrf_token %}
			
			{{ profile_form.as_p }}
			
			<input type="submit" name="submit" value="SaveProfile" />
		</form>

{% endblock %}

templates/rango/register.html
<!--
LEGACY CODE
{% extends 'rango/base.html' %}
{% block body_block %}
		<h1>Register with Rango</h1>
		
		{% if regsitered %}
		Rango says: <strong>thank you for registering!</strong>
		{% else %}
		Rango says <strong> register here!</strong><br />
		
		<form id="user_form" method="post" action="{%url 'rango:register' %}" enctype="multipart/form-data">
		
			{% csrf_token %}
			
			{{ user_form.as_p }}
			{{ profile_form.as_p }}
			
			<input type="submit" name="submit" value="Register" />
		</form>
		{% endif %}
{% endblock %} -->

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block body_block %}
	<div class="page-header">
		<h1> Restricted Page </h1>
	</div>
	<h2> Only logged in users can see this text </h2>
{% endblock %}

templates/rango/search.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title %}Search{% endblock %}
{% block body_block %}
	<div class="page-header">
		<h1>Search with Rango</h1>
	</div>
	
	<div class="row">
		<div class="panel panel-primary">
			<br />
			
			<form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
				{% csrf_token %}
				
				<input class="form-control" type="text" size="50" name="query" value="" id="query" />
				<input class="btn btn-primary" type="submit" name="submit" value="Search" />
				<br />
			</form>
			
			<div class="panel">
				{% if result_list %}
					<div class="panel-heading">
					<h3 class="panel-title">Results</h3>
					
					<div class="panel-body">
						<div class="list-group">
							{% for result in result_list %}
								<div class="list-group-item">
									<h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
									<p class="list-group-item-text">{{ result.summary }}</p>
								</div>
							{% endfor %}
						</div>
					</div>
				{% endif %}
			</div>
		</div>
</div>

{% endblock %}